#ifndef COLORS_HPP
#define COLORS_HPP

#include "Color.hpp"

// exported from https=//coolors.co/fffcf2-ccc5b9-403d39-252422-eb5e28
Color floral_white = Color(255, 252, 242);

Color pale_silver = Color(204, 197, 185);

Color black_olive = Color(64, 61, 57);
Color black_olive_1 = Color(170, 163, 153);
Color black_olive_2 = Color(120, 114, 107);
Color black_olive_3 = Color(31, 27, 22);
Color black_olive_4 = Color(35, 27, 17);

Color eerie_black = Color(37, 36, 34);
Color eerie_black_1 = Color(154, 150, 140);
Color eerie_black_2 = Color(101, 98, 92);
Color eerie_black_3 = Color(23, 20, 16);
Color eerie_black_4 = Color(26, 21, 12);

Color flame = Color(235, 94, 40);
Color flame_1 = Color(255, 159, 124);
Color flame_2 = Color(251, 127, 82);
Color flame_3 = Color(194, 62, 13);
Color flame_4 = Color(154, 42, 0);

Color saffron = Color(235, 190, 40);
Color saffron_1 = Color(255, 225, 124);
Color saffron_2 = Color(251, 212, 82);
Color saffron_3 = Color(194, 153, 13);
Color saffron_4 = Color(154, 118, 0);

Color blue_pigment = Color(55, 47, 164);
Color blue_pigment_1 = Color(116, 110, 198);
Color blue_pigment_2 = Color(81, 73, 175);
Color blue_pigment_3 = Color(35, 27, 135);
Color blue_pigment_4 = Color(21, 14, 107);

Color shamrock_green = Color(28, 162, 101);
Color shamrock_green_1 = Color(95, 197, 151);
Color shamrock_green_2 = Color(57, 173, 120);
Color shamrock_green_3 = Color(9, 134, 77);
Color shamrock_green_4 = Color(0, 106, 58);

/* Generated by Palettoncom © 2002_2014 */
/* http=//palettoncom */

/* SCSS Gradient
$gradient-top= linear-gradient(0deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-right= linear-gradient(90deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-bottom= linear-gradient(180deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-left= linear-gradient(270deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-top-right= linear-gradient(45deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-bottom-right= linear-gradient(135deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-top-left= linear-gradient(225deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-bottom-left= linear-gradient(315deg, #fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
$gradient-radial= radial-gradient(#fffcf2ff, #ccc5b9ff, #403d39ff, #252422ff, #eb5e28ff);
 */

#endif