name: Release

on:
  push:
    branches:
      - main
      - develop
  #  tags:
  #    - 'v*' 

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: deps
        run: sudo apt-get install libgl1-mesa-dev libx11-dev libsamplerate0-dev libsndfile1-dev libjack-jackd2-dev
      - name: make
        run: make -j2
      - name: create-zip
        run: |
          cd /home/runner/work/drops/drops/bin/
          zip -r /home/runner/work/drops_binaries.zip ./* 

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-artifact@v2
        with:
          name: Drops ${{ github.ref }}
          path: /home/runner/work/drops/drops/bin/
          
